version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ortkiv/web:v1
    command: gunicorn foodgramm.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/usr/src/app/web/static/
      - media_value:/usr/src/app/web/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: ortkiv/frontend_web:v1
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
volumes:
  database_value:
  static_value:
  media_value:
