name: foodgram_project_react

on: [push]

jobs:
  tests:
    name: Flake8
    runs-on: ubuntu-latest
  
    steps:
      - name: Clon repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd backend/foodgramm/
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt
      - name: Test with flake8
        run: |
          python -m flake 8
